### ISSUE TITLE
Examples: Universal app w/ React Native +  React Native Web in Next.js + Turbo

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#1119]
### Describe the feature you'd like to request

Add example(s) of a universal app with built React Native, React Native Web, and Next.js with various popular React Native setups

### Describe the solution you'd like

Should be similar to https://github.com/nandorojo/solito/tree/master/example-monorepos/blank. We should connect with React Native experts to determine what libraries / navigation primitives should ship in the example(s). 

### Describe alternatives you've considered

N/A

**Comment by SushritPasupuleti** [comment]
This would be great, I just started using turborepo with the exact same setup in mind, and came here after looking at solito.

**Comment by prometheas** [comment]
My team and I have a React Native mobile app and are about to replace a Python-based API service with a Nest.js reimplementation, which will also have a Next.js backoffice app (and maybe, in future, also a Next.js customer-facing app, though that's less certain).

While it would have been ideal to have already found this at the ready, I'd be interested in participating in any effort that may arise from this issue, fwiw.

**Comment by nandorojo** [comment]
Happy to help here. You’ll likely have the same starter as `solito`, but if you want it to be as bare as possible, we could remove some of the libraries. I would probably remove Dripsy (used for styling), but leave the remaining libs (like Reanimated/Moti) since these are used in most RN apps these days. Depends how low level you want the starter to be.

As for navigation, we could add tabs and drawers and things like that too.
