### ISSUE TITLE
Preloading my environment with dotenv is not working

### ISSUE THREAD

**Issue by alexbjorlig** [vercel/turborepo#1149]
### What version of Turborepo are you using?

1.2.5

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm setting up turborepo, and have an issue with the usage of the [dotenv](https://github.com/motdotla/dotenv) package (`16.0.0`). When I add the following script in my root package.jsons:

```
"build": "node -r dotenv/config ./node_modules/.bin/turbo run build",
```

I get the error:

```
❯ npm run build

> turborepo-basic-shared@0.0.0 build
> node -r dotenv/config ./node_modules/.bin/turbo run build

<full-path>/my-turborepo/node_modules/turbo/bin/turbo:1
����


SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

### Expected Behavior

I expect the command to execute, with the environment preloaded.

### To Reproduce

clone repo [here](https://github.com/alexbjorlig/turbo-env-preload-bug) and run `npm run build`

**Comment by nathanhammond** [comment]
Hey @alexbjorlig! This is not a pattern that will work. `./node_modules/.bin/turbo` is a binary Go application. Node is *very* confused as to why you're passing it a compiled executable Go file which is why it is returning an error.

If you're looking to use this approach, `set -o allexport && source .env` will likely get you what you need. (In other words, you will need to specifically ensure that the environment variables are set at the shell level.)

**Comment by nathanhammond** [comment]
Thanks for following up with the solution that worked for you!
