### ISSUE TITLE
Yarn 3 turborepo installer trying to set registry for yarn 1 syntax

### ISSUE THREAD

**Issue by tvarwig** [vercel/turborepo#1288]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

When having yarn 3.x installed the turborepo installer is aborting the install process with the following error. `yarn install --registry= has failed.` From What I understand Yarn 2 and 3 uses the syntax `yarn config set registry <url-to-your-registry>` in lieu of `yarn install --registry=`

Does the installer know which version of yarn is installed / used?

### Expected Behavior

To Install with yarn 3.

### To Reproduce

`npx create-turbo@latest`
Choose `yarn`

**Comment by tknickman** [comment]
Installing from an explicit registry was added via https://github.com/vercel/turborepo/pull/885 because installing from the default could be slow for users in some regions. 

The custom registry that is used is already [pulled from the users config](https://github.com/vercel/turborepo/blob/main/packages/create-turbo/src/index.ts#L301-L305), so for yarn v2+ we can just make this a noop.
