### ISSUE TITLE
Always getting cache miss during TurboRepo <> CircleCI integration

### ISSUE THREAD

**Issue by mkotsollaris** [vercel/turborepo#1343]
### What version of Turborepo are you using?

1.2.16

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

After following the detailed guide of [CircleCi + TurboRepo integration](https://turborepo.org/docs/ci/circleci), I am getting cache miss all the time, even though I am pretty sure I have configured CircleCI secrets accordingly. Here's [my repo](https://github.com/mkotsollaris/turbo-example)+ [CircleCi logs](https://app.circleci.com/pipelines/github/mkotsollaris/turbo-example/8/workflows/98a01724-186c-480f-819b-fd4b872bbb7f/jobs/11).

### Expected Behavior

Should receive `cache hit` for identical job execution.

### To Reproduce

- Rerun job in circleCI
- observe `cache miss` for identical job, instead of `cache hit`

**Comment by tknickman** [comment]
This appears to be an issue with how CircleCI environment variables work. 

Because we're setting the environment variables [on the project](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project), you actually don't need to specify them in the workflow. Adding these in the workflow is overriding the variables set on the project [because they have a higher precedence](https://circleci.com/docs/2.0/env-vars/#order-of-precedence), so the environment variables literally end up being the strings `$TURBO_TEAM` and `$TURBO_TOKEN`, and your remote cache requests are failing to authenticate.

To fix this, just remove [these lines](https://github.com/mkotsollaris/turbo-example/blob/main/.circleci/config.yml#L13-L15), but make sure the correct variables _are_ set in your project settings as described [here](https://turborepo.org/docs/ci/circleci#remote-caching).

Apologies for the error on the docs here - we will get this updated!

**Comment by mkotsollaris** [comment]
thank you for the quick fix @tknickman!
