### ISSUE TITLE
turbo run dev --parallel - max port 3009

### ISSUE THREAD

**Issue by mindyourlifeguide** [vercel/turborepo#1579]
### What version of Turborepo are you using?

^1.3.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

max port 3009 
![image](https://user-images.githubusercontent.com/35348648/180860938-2f40982c-568a-464a-acec-9d7035fdb28b.png)

### Expected Behavior

port auto generate +1 - 3010, 3011, etc.

### To Reproduce

setup 11 projects in monorepo and run `turbo run dev --parallel`

**Comment by weyert** [comment]
Do you have a reproducible case of this?

**Comment by tknickman** [comment]
This is likely a result of what your dev script is doing, not `turbo` - could you share the command you're running?

**Comment by gaspar09** [comment]
Most likely failing because your `next dev` scripts are trying to re-use ports. Try setting the Port for some of your apps.
 
If you're curious here's the auto-assign for next.js  https://github.com/vercel/next.js/blob/85cc454023aa36c86602db9110e7377704b62e53/packages/next/server/lib/start-server.ts#L21-L35
