### ISSUE TITLE
turbo run build --graph=my-graph.png not working

### ISSUE THREAD

**Issue by JacobWeisenburger** [vercel/turborepo#1887]
### What version of Turborepo are you using?

1.4.6

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

when I do `turbo run build --graph=my-graph.png` it doesn't make an image file.

### Expected Behavior

I should get an image with the graph

### To Reproduce

```
$ turbo run build --graph=my-graph.png

 WARNING  `turbo` uses Graphviz to generate an image of your    
graph, but Graphviz isn't installed on this machine.

You can download Graphviz from https://graphviz.org/download.   

In the meantime, you can use this string output with an
online Dot graph viewer.

digraph {
        compound = "true"
        newrank = "true"
        subgraph "root" {
                "[root] ___ROOT___#build" -> "[root] ___ROOT___"
                "[root] docs#build" -> "[root] tsconfig#build"  
                "[root] docs#build" -> "[root] ui#build"        
                "[root] tsconfig#build" -> "[root] ___ROOT___#build"
                "[root] ui#build" -> "[root] tsconfig#build"
                "[root] web#build" -> "[root] tsconfig#build"
                "[root] web#build" -> "[root] ui#build"
        }
}
```

**Comment by JacobWeisenburger** [comment]
I have graphviz installed

![image](https://user-images.githubusercontent.com/31667350/189158629-33f98432-6cc0-4f9a-8bae-04bcd72334de.png)

**Comment by tknickman** [comment]
Hmm got it - thanks for that info - [this is how we check graphviz is installed](https://github.com/vercel/turborepo/blob/main/cli/internal/graphvisualizer/graphvisualizer.go#L24-L28), can you ensure this is working outside the context of turbo by running:

```
dot -v
```

and ensuring you get return?

For example on my system this looks like:
```
1 > dot -v
dot - graphviz version 3.0.0 (20220226.1711)
libdir = "/opt/homebrew/Cellar/graphviz/3.0.0/lib/graphviz"
Activated plugin library: libgvplugin_dot_layout.6.dylib
Using layout: dot:dot_layout
Activated plugin library: libgvplugin_core.6.dylib
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
	/opt/homebrew/Cellar/graphviz/3.0.0/lib/graphviz/config6
		was successfully loaded.
    render	:  cairo dot dot_json fig gd json json0 map mp pic pov ps quartz svg tk visio vml vrml xdot xdot_json
    layout	:  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout	:  textlayout
    device	:  bmp canon cgimage cmap cmapx cmapx_np dot dot_json eps exr fig gd gd2 gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg json json0 mp pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vdx vml vmlz vrml wbmp webp xdot xdot1.2 xdot1.4 xdot_json
    loadimage	:  (lib) bmp eps gd gd2 gif jpe jpeg jpg pdf png ps svg webp xbm
```

This is likely going to look different since you're on Windows. 

Also, if you're immediately blocked by this - [here is your graph](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0A%20%20%20%20%20%20%20%20compound%20%3D%20%22true%22%0A%20%20%20%20%20%20%20%20newrank%20%3D%20%22true%22%0A%20%20%20%20%20%20%20%20subgraph%20%22root%22%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20___ROOT___%23build%22%20-%3E%20%22%5Broot%5D%20___ROOT___%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20docs%23build%22%20-%3E%20%22%5Broot%5D%20tsconfig%23build%22%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20docs%23build%22%20-%3E%20%22%5Broot%5D%20ui%23build%22%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20tsconfig%23build%22%20-%3E%20%22%5Broot%5D%20___ROOT___%23build%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20ui%23build%22%20-%3E%20%22%5Broot%5D%20tsconfig%23build%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20web%23build%22%20-%3E%20%22%5Broot%5D%20tsconfig%23build%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20web%23build%22%20-%3E%20%22%5Broot%5D%20ui%23build%22%0A%20%20%20%20%20%20%20%20%7D%0A%7D) from an online generator!

**Comment by JacobWeisenburger** [comment]
I tried to install graphviz twice from [here](https://graphviz.org/download/), but it still doesn't work.

These are the installers I tried:
[graphviz-5.0.1 (64-bit) EXE installer](https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/5.0.1/windows_10_cmake_Release_graphviz-install-5.0.1-win64.exe)
[graphviz-4.0.0 (64-bit) EXE installer](https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/4.0.0/windows_10_cmake_Release_graphviz-install-4.0.0-win64.exe)

**Comment by gsoltis** [comment]
Not 100% sure this will fix the issue, but it looks like we were using the wrong flag in our graphviz-detection check. If you run `dot -V` from the terminal, do you get a version displayed?

Flag fix: https://github.com/vercel/turborepo/pull/1954

**Comment by JacobWeisenburger** [comment]
![image](https://user-images.githubusercontent.com/31667350/190415289-e0b63b25-0939-4bf0-8232-e954bb03a526.png)

![image](https://user-images.githubusercontent.com/31667350/190415422-c7b49aca-8eb2-4fd7-83d6-626d2552cba7.png)

**Comment by gsoltis** [comment]
Hmm, I tried the `5.0.1` installer linked above and got:
```
C:\Users\greg>dot -V
dot - graphviz version 5.0.1 (20220820.1526)
```
I did have to start a new terminal to pick up an updated `%PATH%` variable, maybe that's the problem?


@JacobWeisenburger can you determine how to run graphviz normally on your system? Then we can probably update our check to account for it.

**Comment by JacobWeisenburger** [comment]
I was able to get it working. I think it was because I didn't add to the system PATH.

![image](https://user-images.githubusercontent.com/31667350/190655385-409c859d-7b51-4eb5-8a51-3e8da95cec46.png)

When I did this, it worked:
![image](https://user-images.githubusercontent.com/31667350/190655593-7b111523-2e75-4868-a970-cc448e76f0f1.png)
