### ISSUE TITLE
--no-cache parameter doesn't work properly when used without --parallel

### ISSUE THREAD

**Issue by andreyluchianic** [vercel/turborepo#2167]
### What version of Turborepo are you using?

1.5.4

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When i run simple build command with `--no-cache` option i get cached response. example:
```bash
yarn turbo run build --filter=...mal-practice --no-cache
yarn turbo run build --filter=mal-practice... --no-cache
yarn turbo run build --filter=mal-practice --no-cache
```
what interesting is that when i add `--parallel` option to same command it works as expected 
```bash
yarn turbo run build --filter=...mal-practice --parallel --no-cache
```

### Expected Behavior

As said in [documentation](https://turborepo.org/docs/core-concepts/caching#turn-off-caching)
**To entirely disable caching, append --no-cache to any command:**

### To Reproduce

sorry can't provide my repository it's in private org but i think this have nothing to do with repository code. also my turbo config is simple as that. 
```
    "build": {
      "dependsOn": [
        "^build"
      ],
      "outputs": [
        "dist/**"
      ]
    },
    ....
    ```

**Comment by gsoltis** [comment]
I think this is working as intended. `--no-cache` causes `turbo` to "Avoid saving task results to the cache." You likely have cached results from some run that did not specify `--no-cache`. If you want to _force_ script execution, regardless of what's in the cache, use `--force`.

`--parallel` is causing cache misses because it is changing the dependency graph. You are no longer waiting for dependencies, so `turbo` calculates a different hash for each task, causing a cache miss. Further specifying `--no-cache` in that situation means that the execution won't be written to the cache, resulting in continuing cache misses with `--parallel`.
