### ISSUE TITLE
[turborepo] Logging colors are non-deterministic

### ISSUE THREAD

**Issue by preynal** [vercel/turborepo#2564]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

CLI colors are changing between runs for the same package. 
It sure looks pretty for VC demos, but is very confusing, as a user expects the package name to have the same color between consecutive runs.

<img width="490" alt="Screenshot 2022-11-02 at 17 22 32" src="https://user-images.githubusercontent.com/1218704/199544852-ba27bb28-8ef9-47d1-a6fb-21d18b9925e4.png">

<img width="302" alt="Screenshot 2022-11-02 at 17 23 05" src="https://user-images.githubusercontent.com/1218704/199544921-d549c03f-7fb9-455f-8b81-bc655c59f3bc.png">

### Expected Behavior

Colors of a package name in the CLI must remain the same no matter when or where you run the CLI

### To Reproduce

Run a turbo repo command twice, the colours will randomly change.

**Comment by mehulkar** [comment]
I believe this is not deterministic because the order of tasks running is also not deterministic (by design). We could base the color on the task name itself to make it deterministic, but I'm not sure how we'd support an unbounded number of colors (I'm sure it's possible, just not sure off the top of my head what's available)

The code is here:

https://github.com/vercel/turbo/blob/261d22177f6c7301f9c5e93518112b025b15d7aa/cli/internal/colorcache/colorcache.go#L33-L45

**Comment by scamden** [comment]
wouldn't have to be unbound could just hash to an integer and modulus to the number of colors to least stay consistent. just a thought (i noticed this even for a single task)

**Comment by jtlapp** [comment]
I just had a build fail and was left typing invisible characters into the shell prompt. My background was black, so maybe the characters were also black.

**Comment by Hacksore** [comment]
What's even more undesirable is even the replayed output from a `>>> FULL TURBO` cached run does not yield a deterministic color 😢.

I'd imagine with the port to rust it would be a good idea to make the color be derived from the package/task name.

cc @anthonyshew since were talking about this the other day.

**Comment by opiredev** [comment]
@nabby27 created a $50.00 reward using [Opire](https://opire.dev) 
 <details><summary>How to earn this reward?</summary>

Since this project does not have Opire bot installed yet 😞 you need to go to [Opire](https://app.opire.dev) and claim the rewards through your programmer's dashboard once you have your PR ready 💪</details>

**Comment by anthonyshew** [comment]
@Shaharking was awesome and got this fixed up in https://github.com/vercel/turborepo/pull/9023.

While task colors aren't fully deterministic _at all times_ with this change, they're deterministic when you run the same graph multiple times, which is likely what most folks are looking for and what we're reasonably capable of doing.

Thanks again, @Shaharking!

**Comment by ugreg** [comment]
Hello @preynal @anthonyshew or @Shaharking now that this is closed can the bounty also be removed from here? https://app.opire.dev/issues/01HWTN2QCK0GHX1146FZC0CWSY?
