### ISSUE TITLE
Storybook hangs when run from turbo

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#422]
### Discussed in https://github.com/vercel/turborepo/discussions/374

<div type='discussions-op-text'>

<sup>Originally posted by **fibonacid** December 17, 2021</sup>
### What version of Turborepo are you using?

1.0.17

### What version of Node are you using?

v14.17.6

### What version of Yarn are you using?

1.22.4

### Describe the Bug

Can't run `build-storybook` on ui package using turbo.

### Expected Behavior

Running build-storybook from ui package works fine.

```bash
yarn --cwd packages/ui build-storybook
```

Running build-storybook using turbo gets stuck forever.

```bash
yarn build-storybook
```

### To Reproduce

Clone [example repo](https://github.com/fibonacid/turborepo-build-storybook-bug)
```bash
git clone https://github.com/fibonacid/turborepo-build-storybook-bug
cd turborepo-build-storybook-bug
```

Install dependencies
```bash
yarn install
```

Run command
```bash
yarn build-storybook
```</div>

**Comment by jaredpalmer** [comment]
This is a due to #336 and/or #292

**Comment by kylemh** [comment]
I don't think it's due to circular dependencies.

If I only have one package (ui) and its "build" script is `build-storybook`, I still run into this issue.

As pointed out [here](https://github.com/vercel/turborepo/discussions/374#discussioncomment-1865933), adding the `--quiet` flag to the build script seems to resolve the issue.

**Comment by fibonacid** [comment]
@kylemh confirm, adding the quiet flag resolved the issue for me.
https://github.com/fibonacid/turborepo-build-storybook-bug/tree/b1d9fb90a5977312175da15895d036f84c43db6f

**Comment by jaredpalmer** [comment]
I think the issue could also be with Go’s io.MultiReader which turbo uses to stitch together stdout and stderr as one stream. Despite its name, this function actually concats the streams though. What seems to happen sometimes when only stderr prints is that turbo locks up. 

I’ve noticed this with rollup watch mode too.

The sad news is that there isn’t a great solution for when we need to keep around prefixed lerna-style streamed logs other than turbo stitching stderr into stdout or stdout into stderr as one bytestream.

**Comment by kylemh** [comment]
What do you think about - in the meantime - adding a FAQ about Storybook. 

I'm sure there will be an example in soon!

**Comment by weyert** [comment]
Yeah, similar issue when using `--watch` with Jest.

**Comment by guillaumewuip** [comment]
Similar issue with jest (even without `--watch`) and a webpack long build too.

**Comment by rebelchris** [comment]
I have a similar issue in jest (no watch) as well.
One of the packages eventually will go on, but one just seems to stop no log just stuck in oblivion

**Comment by killpowa** [comment]
I am running into this issue too, I have a turborepo project with multiple sveltekit projects and they won't start because of a few errors/warnings on startup which make turborepo hang. Going into each specific sveltekit project and running it individually works just fine. Any way I can fix this while waiting for an official fix?
