### ISSUE TITLE
`turborepo` does not propagate the `SIGINT` signal event.

### ISSUE THREAD

**Issue by vorillaz** [vercel/turborepo#444]
### What version of Turborepo are you using?

1.0.23

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

On most node.js applications is a common practise adding a cleanup handler in order to close open DB connections
Turborepo does not seem to propagate the exit signals from the CLI towards the applications running.

### Expected Behavior

Once upon `SIGINT` gets triggered I would expect all the open applications to grab the signal in order to do some cleanup.

### To Reproduce

The bug is reproducible through the [`kitchen-sink`](https://github.com/vercel/turborepo/blob/main/examples/kitchen-sink/apps/api/src/server.ts) example, just add a "graceful shutdown" hook in the Express.js application as described in the [official documentation](https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html)

**Comment by jaredpalmer** [comment]
Confirmed. Thanks for the write up! Over the weekend I researched the solution: we need to call cmd.ExecWithContext and have all task commands share a context as well as use a signal and channel to listen to SIGINT and trigger cleanups. 

This could also be possibly related to #205, but I’m not sure

**Comment by gsoltis** [comment]
For SIGINT specifically (keyboard interrupt), the signal is actually delivered to all child processes and graceful cleanups *are* run. However, the output for all of the child processes is routed via `turbo`, which does not currently have a signal handler installed. You can verify this by changing your shutdown handler to do something like write to a file.

I ran an experiment based on your suggestion of adding the graceful shutdown to `apps/api` in `kitchen-sink`:
```javascript
const runningServer = server.listen(port, () => {
  log(`api running on ${port}`);
});
process.on("SIGINT", () => {
  log("SIGINT signal received: closing HTTP server");
  runningServer.close(() => {
    log("HTTP server closed");
    fs.writeFileSync("sigint", "exited");
  });
});
```

Run `yarn dev` in `kitchen-sink`, and after everything is running hit `Ctrl+C` to send `SIGINT`. Output will stop immediately, because it is routed via `turbo`. However, you should find the `sigint` file in `apps/api`. @vorillaz  Can you verify whether your handlers are *actually* not running, or if you are just unable to see the output? If they are actually not running, can you describe how you are sending the `SIGINT` signal?

It's possible that `turbo` needs to handle other signals, but I think this is separate from the issue of propagating a failure that results from running a task like in #470

**Comment by vorillaz** [comment]
Hey @gsoltis thanks for the feedback, I definitely cannot see the output on my dev environment but that's not my main concern.  As I am using turborepo to spin up individual process I am facing open ports when I am using `Ctrl + C` in order to stop the monorepo. More precisely I am using [`fastify-graceful-shutdown`](https://www.npmjs.com/package/fastify-graceful-shutdown) in order to free the server's port, upon restarting the ports are still bound and I can see there are db connections hanging.

**Comment by gsoltis** [comment]
@vorillaz When you use `Ctrl+C` to stop the monorepo, can you verify that all of the server processes have in fact exited? I wonder if one of them might be hanging, but you can't see it due to `turbo` having exited. If nothing else, the OS should close the connection to the database when the process exits, so it's an indication that it might still be running.

One thing I am considering is having `turbo` wait for child processes to exit upon receiving `SIGINT`, since I think that would help diagnose scenarios like this one.

I will also see if I can reproduce the issue with `fastify-graceful-shutdown`.

**Comment by gsoltis** [comment]
@vorillaz quick update on results of my `fastify` experiment. I am to reproduce this behavior *if* I block the thread in the graceful shutdown handler:
```javascript
fastify.after(() => {
  fastify.gracefulShutdown((signal, next) => {
    while (true) {}
  });
});
```
In this case, after hitting `Ctrl+C`, my node process was visible in the output of `ps`, and subsequent attempts to start the process hit the port reuse error.

Is it possible that you are doing something blocking in your shutdown handler? Can you check `ps` after `Ctrl+C`?
