### ISSUE TITLE
ignore flag doesn't work

### ISSUE THREAD

**Issue by jeetiss** [vercel/turborepo#445]
### What version of Turborepo are you using?

1.0.23

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

`turbo run build --ignore='package/path'` doesn't ignore build for `package/path`

### Expected Behavior

`turbo run build --ignore='package/path'` run build for all packages except `package/path`

### To Reproduce

ignore some package and run build

**Comment by kieranm** [comment]
If it's helpful I can't get this to work either. I've tried...

- Using `node_modules/.bin/turbo run build` and `yarn turbo run build`
- With and without `--no-deps`
- With and without `--scope`
- Different glob patterns e.g. `--ignore="apps"` `--ignore="apps/**` `--ignore="apps/**/*`

I'm having to resort to exhaustively listing the packages I do want to build with `--scope` because they don't all have a common prefix.

Thanks!

**Comment by kieranm** [comment]
Just wanted to type up some thoughts. I've ran into multiple issues with this.

Looking into this a bit further, it should be possible to achieve this using a glob on `--scope`. `--ignore` only really seems to apply to changed files.

For example, to exclude packages beginning with `@daybridge/app-`, I would expect to be able to say:

```
turbo run build --no-deps --scope="@daybridge/\!(app-)*"
```

However, the glob library that Turborepo uses appears to be limited, and doesn't support `!` on anything other than single characters in a range. So the above glob doesn't actually work. Someone filed an issue for it [here](https://github.com/gobwas/glob/issues/47).

This seems to be at odds with what [the documentation says](https://turborepo.org/docs/reference/command-line-reference#--ignore) because the negation operator `!` doesn't seem to do anything unless it's inside a `[]` range. It doesn't seem to negate any arbitrary group as the documentation suggests. Something like...

```
turbo run build --no-deps --scope="@daybridge/[\!app]*"
```

sort of works, but excludes all packages beginning with `a` and `p` - which is not the desired behaviour.

In addition, because of a function called [`hasMeta`](https://github.com/vercel/turborepo/blob/c1f1144613dba074b1e691fbdf9621827414f05c/cli/internal/util/filter/filter.go#L51) in the source code, something like...

```
turbo run build --no-deps --scope="@daybridge/{auth,theme}"
```

would not work because `hasMeta` only checks for the presence of `?`, `*` and `[`. If none of these characters are present then the glob is not parsed at all.

If the glob doesn't match any packages, Turbrorepo seems to build everything - which feels bit unintuitive to me. I would expect it to build nothing or error. Maybe there is some historical context I am missing.

Apologies if I'm missing something obvious here!

**Comment by AlonMiz** [comment]
agree, basically i would summarize that it would be nice to have an opposite flag for  `--scope`
instead of  --scope all I want, I can `--exclude` what I don't want
`pnpm turbo run lint --scope="@wow/app" --scope="@wow/web"`
i can write
`pnpm turbo run lint --exclude="@wow/types"`
exclude can be replaced with ignore/filter or something more clear

**Comment by ragrag** [comment]
@jeetiss would be nice if you can share some workaround you found for this

**Comment by jeetiss** [comment]
I did find any workaround for this. It is still broken

**Comment by ndom91** [comment]
Still having this issue as well, nothing I've tried has successfully been able to ignore individual `@org/pkg` type packages. 

For example, we have a bunch of `@next-auth/*-adapter` type packages in our `/packages` directory. I'm trying to run tests like so, `turbo run test --scope=@next-auth/*-adapter --ignore=@next-auth/pouchdb-adapter`. The goal being, to run all adapters _except_ the pouchdb one.

Like the OP, I've tried it with the path name, package.json `name` field, with and without glob stars prefixed and suffixed, etc. None of them did the trick :shrug:

**Comment by morriq** [comment]
@jaredpalmer please check this out 😇

**Comment by morriq** [comment]
on mac with `!` it even not execute command:

`pnpm turbo run  build --scope="!webapp"`  

> zsh: event not found: webapp

--

`pnpm turbo run  build --scope="@lib/**"`

> • Packages in scope: @lib/aa, @lib/bb, webapp1, webapp2

and it runs on webapp1 and webapp2

--

`pnpm turbo run  build --scope="webapp1"`

> • Packages in scope: webapp1

and it runs only on webapp1

**Comment by vtereshyn** [comment]
The issue still appears. I wasn't able to ignore packages using:
- package name
- path to folder

**Comment by paul-vd** [comment]
I'm having same issue, ignore does not seem to work.

Using this to negate the scope
```zsh
 --no-deps --scope='!excluded-app'
```

----

> on mac with `!` it even not executes command:
> 
> `pnpm turbo run build --scope="!webapp"`
> 
> > zsh: event not found: webapp

@morriq  Is that not zsh related? try with single quotes

**Comment by danielweck** [comment]
I am experiencing the same issues as above. This is currently a blocker bug in my dev workflow :(
I just need to be able to exclude package name(s) or folder path(s) from a Turbo task run.

**Comment by Pagebakers** [comment]
I posted this originally: https://github.com/vercel/turborepo/issues/398

Still having issues ignoring packages in my build with 1.1.5 unfornunately.

**Comment by Chrischuck** [comment]
Same issue here, ignore does not work.

**Comment by brunojppb** [comment]
I can also confirm. We are also encountering this issue in our projects.
Currently running Turbo `v1.1.6`.
CC: @ekaitzht-n26

**Comment by claycoleman** [comment]
I managed to get this working using `--scope="\!something-*"`. Note the escaped `\!` due to zsh.

**Comment by emroot** [comment]
I'm having the same issue. Been running this command line `npx turbo run build --scope="@bdqe/api" --scope='!@bdqe/trivia'` and it still runs my `build` script in `packages/trivia`. 
`packages/trivia` calls `packages/api` as a shared dependency. but not the other way around. 
would love some guidance on what I'm doing wrong

**Comment by kieranm** [comment]
@emroot You might need to add `--no-deps` if `trivia` depends on `api` and you only want to build `api` and not `trivia`.

**Comment by emroot** [comment]
that helped thanks!

**Comment by kieranm** [comment]
I suspect this issue could probably be closed now the new `--filter` syntax has been released:
https://turborepo.org/blog/turbo-1-2-0

**Comment by jeetiss** [comment]
thanks, everything works like a charm with the `--filter` option

**Comment by panieldark** [comment]
For everyone who experiences this even with the `--filter` option with a `zsh: event not found:` error, **escape the !** like so:
`turbo run build --filter="\!@scope/package"`
