### ISSUE TITLE
[turborepo] `turbo prune` does not consider `.pnpmfile.cjs`

### ISSUE THREAD

**Issue by pkerschbaum** [vercel/turborepo#5927]
### What version of Turborepo are you using?

1.10.13

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

pnpm allows to modify the dependencies of any workspace via the `readPackage` hook of `.pnpmfile.cjs` (see also <https://pnpm.io/pnpmfile#hooksreadpackagepkg-context-pkg--promisepkg>).  
If this `readPackage` hook _adds_ a dependency to a workspace, and then `turbo prune` is run, the pruned lockfile `pnpm-lock.yaml` does not contain these dependencies anymore.

### Expected Behavior

`turbo prune` should consider the modifications done by the `readPackage` hook.

I wonder if `turbo prune` could, in case of a pnpm monorepo, just get the dependency information from `pnpm-lock.yaml#importers` field instead of the `package.json` of the respective workspace.  
Because that has the _actual_ information which dependencies every workspace needs.

### To Reproduce

- Check out the reproduction repo.
- `pnpm install`
- `pnpm run test`
  - → the pruned lockfile (location `../pruned-monorepo/pnpm-lock.yaml`) does not contain an entry for `glob`, although it was added as a dependency via `pnpmfile.cjs`

### Reproduction Repo

https://github.com/pkerschbaum/turbo-issue-prune-does-not-consider-pnpmfile-cjs

**Comment by chris-olszewski** [comment]
Can you share what you're working around that you can't declare a dependency in your workspace's `package.json` and instead need to inject via that hook? I believe that hook and it's less powerful (but easier to understand) cousin [`packageExtensions`](https://pnpm.io/package_json#pnpmpackageextensions) are primarily used for sources where you don't control the `package.json`.

> I wonder if turbo prune could, in case of a pnpm monorepo, just get the dependency information from pnpm-lock.yaml#importers field instead of the package.json of the respective workspace.
Because that has the actual information which dependencies every workspace needs.

This is possible, but it would require special casing our handling of the `pnpm` lockfile since not all lockfiles contain this information. I do not have capacity to implement this change, but accept a PR and give code pointers.

**Comment by chris-olszewski** [comment]
Closing as no author response for over a year.
