### ISSUE TITLE
Prune is not supported for Bun

### ISSUE THREAD

**Issue by joshunrau** [vercel/turborepo#5982]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Support `turbo prune` when using bun.

### Describe the solution you'd like

Running `turbo prune` should work with bun the same as with npm.

### Describe alternatives you've considered

Not using bun or not using turbo

**Comment by nathanhammond** [comment]
We're aware of this limitation. Serializing to the binary Bun lockfile format is a non-trivial task and not imminently forthcoming.

For now, if you want to use `turbo prune` for a Bun project, you can losslessly use it with either `yarn` or `pnpm`. We recommend choosing `yarn` because the `node_modules` layout is most-similar to Bun and it is more-likely to be compatible with your project.

```sh
cd ./path/to/bun/project
bunx @turbo/workspaces@latest convert ./ yarn --skip-install
turbo prune
```

If you don't want any of the automated changes to be permanent you can then proceed to revert all changes in the repository.

Note that the output pruned repository must use the package manager you select (`yarn` or `pnpm`)—it cannot use `bun`.

**Comment by jordanebelanger** [comment]
> Note that the output pruned repository must use the package manager you select (`yarn` or `pnpm`)—it cannot use `bun`.

Doesn't bun support the yarn lockfile format? Why the need to switch package manager even after converting a bun.lockb to a yarn lockfile?

P.S would love for this issue to get attention, this is the last blocker for us to move over to bun as our package manager.

**Comment by chris-olszewski** [comment]
Bun supports serializing the `bun.lockb` to a `yarn.lock` to make it human readable, but it doesn't support using parsing a `yarn.lock` or creating a `bun.lockb` from a `yarn.lock`.

There's some chatter around `bun` getting support for using a `package-lock.json` and that could open a path forward to `turbo prune` supporting `bun`.

**Comment by wladpaiva** [comment]
Bun supports a human readable lock file now
https://bun.sh/guides/install/yarnlock

Maybe an easy fix would be to have an option for turbo to read specific lock files the same way bun does
`turbo prune --yarn`

**Comment by thecrabcode** [comment]
Is there any update on this guys?

**Comment by AirP0WeR** [comment]
+1 to this problem

**Comment by baptisteArno** [comment]
YES please 🙏
