### ISSUE TITLE
Possible to move .turbo directories to the cache?

### ISSUE THREAD

**Issue by betaorbust** [vercel/turborepo#727]
### Describe the feature you'd like to request

Currently, turborepo adds `.turbo` directories to every workspace package. My understanding from the docs and poking around is that this is used for log caching (and maybe other things?) 
I'd like to see if it's possible to move these into the cache directory itself, cleaning up project structure and being a bit less intrusive.

### Describe the solution you'd like

Move the .turbo directory contents into a structure in the cacheDir instead of in the workspace directories.

### Describe alternatives you've considered

It seems like it might be possible to store the logs under the cache directories for the associated hash of an action, but maybe if that's not possible, reflecting the package directory structure in a dedicated directory in the root of the cacheDir could work.

Thanks for this awesome project!

**Comment by jaredpalmer** [comment]
Seems legit.

**Comment by KevinRouchut** [comment]
Indeed these many `.turbo` directories make the structure of the project less clean.

It would seem that .turbo directories are useless, because they are already present in the archive files here: `node_modules/.cache/turbo/{hash}.tar.zst`.
Also if I delete these .turbo directories, FULL TURBO works, cached outputs works, everything works correctly, unfortunately .turbo directories are created again...

**Comment by tknickman** [comment]
You can now change this via setting [--cache-dir](https://turbo.build/repo/docs/reference/run#--cache-dir-path)

**Comment by artursudnik** [comment]
> You can now change this via setting [--cache-dir](https://turbo.build/repo/docs/reference/run#--cache-dir-path)

Although it is possible to change the main `.turbo` folder location, every package within the repository has a `.turbo` folder created.
