### ISSUE TITLE
Missing framework env vars in default pass through

### ISSUE THREAD

**Issue by mauricewegner** [vercel/turborepo#8375]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

npx create-turbo@canary -e with-vue-nuxt

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.3

### Describe the Bug

Currently [Framework Environment Variables](https://vercel.com/docs/projects/environment-variables/system-environment-variables#framework-environment-variables) do not get passed through for all frameworks besides next.

https://github.com/vercel/turbo/pull/8359 only added support for Next.js.

Env vars like NUXT_ENV_VERCEL_GIT_COMMIT_REF are undefined.

### Expected Behavior

[Framework Environment Variables](https://vercel.com/docs/projects/environment-variables/system-environment-variables#framework-environment-variables) should be defined as expected.

### To Reproduce

Clone a framework example and deploy to Vercel.

**Comment by anthonyshew** [comment]
I'm unable to reproduce this using the instructions you've provided. Steps I used:
1. Got started with `npx create-turbo@latest -e with-vue-nuxt`
2. Created a repository on GitHub for the code
3. Made a small edit to print `env` by editing the `build` script in `package.json` (e.g. `"env && nuxt build"`)
4. Deployed to Vercel using GitHub integration

Here is part of my log:

![CleanShot 2024-06-07 at 10 40 06](https://github.com/vercel/turbo/assets/35677084/96de9956-8cbb-4be9-a0bd-d2ff9431785b)


You can see that the variable you're referencing, `NUXT_ENV_VERCEL_GIT_COMMIT_REF`, is indeed defined inside of the `turbo` invocation.

It's important to note that Framework inference, by itself, will make the environment variable available. It does not *also* need to be passed through. Passthrough is an escape hatch for environment variables that are [meant to be available but not affecting hashing](https://turbo.build/repo/docs/reference/configuration#passthroughenv).

Therefore, if a variable is in *one of* `env` or `passthroughEnv` it will be available. Because variables that start with `NUXT_ENV_*` are included in Framework Inference, they are included in `env`.

I'd also like to be more clear that #8359 is not Next.js-specific. While there are a few variables listed that _are_ highly specific to hyper-optimizing Next.js on Vercel-specific infrastructure, we went through a process of discovery that showed us the changes in #8359 have positive outcomes for all frameworks on Vercel **and** no (reasonable) ramifications on any usage of `turbo` away from Vercel.

We work hard to build a low coupling, high cohesion build system for anyone to use, with an optional path to zero-configuration caching on Vercel. If you're able to show a reproduction where this isn't the case, I'd appreciate you sharing so we can fix it.

**Comment by anthonyshew** [comment]
If you'd like to upgrade to 2.0 without worrying about environment variables immediately, you can add `--env-mode=loose` and choose to handle those variables later on. From the upgrading guide: https://turbo.build/repo/docs/crafting-your-repository/upgrading#update-turbo-run-commands

**Comment by anthonyshew** [comment]
A question: Are you looking for Framework Inference to be happening in a dependent package, rather than the Nuxt application itself? Note that Framework Inference is per-package, so those environment variables won't be available during the package's build and will be available during the Nuxt's application's build.

**Comment by anthonyshew** [comment]
Ah, great to hear it! Stay shippin'!
