### ISSUE TITLE
Scrolling is not possible with a Trackpad in Webstorm

### ISSUE THREAD

**Issue by MickL** [vercel/turborepo#8427]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

-

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.3

### Describe the Bug

Scrolling is not possible with a Trackpad at least on macOS.

Initially I can scroll up once but then I cant scroll down anymore, the frame jumps up to the very top multiple times per second. I reported this many times in the UI feedback of 1.x canary.

This occurs at least in Webstorm. I tested in iTerm and there trackpad scrolling seems to work.

Additionally the UI adds tons of signs:
<img width="965" alt="338526919-1c7ecbc3-fccd-4b55-8ef2-64af4ded8faa" src="https://github.com/vercel/turbo/assets/5103210/d6f306b8-c8b8-421d-a404-4316accc9e1f">

### Expected Behavior

-

### To Reproduce

-

**Comment by chris-olszewski** [comment]
This looks very similar to a this user's comment: 

> This is still affecting me. When I scroll with trackpad it goes through my history. ctrl + arrow / pg up + down produces "A" (shift arrow up) and "B" (shift arrow down)

[Source](https://youtrack.jetbrains.com/issue/IJPL-106240/Scroll-up-down-in-Terminal-with-Shortcut-Linux#focus=Comments-27-8069658.0-0)

My bet is that Webstorm is intercepting mouse events and translating mouse scroll to up/down errors. That would explain your behavior of
> When I scroll it toggles throught the items in the sidebar

since we use arrow keys to move between tasks in the list.

If this is the case, there's not much we can do especially since we can't look at the Webstorm source code. Only work around I can offer you is `Ctrl-p`/`Ctrl-n` for scrolling without the mouse.

**Comment by MickL** [comment]
You might get in contact with Webstorm and try to find a solution together. I am sure they are open to work together to support Turbo as good as possible.

**Comment by FadiObaji** [comment]
@MickL Open settings and type `mouse` in the search box, then go to `terminal` under tools on the left side, you'll see `Mouse reporting` checked. Uncheck it.

![Screenshot 2024-12-22 210856](https://github.com/user-attachments/assets/46040a9d-092e-4c09-a541-53a20a4a0cd2)
