### ISSUE TITLE
dependsOn is not respected when using --scope

### ISSUE THREAD

**Issue by IPWright83** [vercel/turborepo#860]
### What version of Turborepo are you using?

1.1.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I'm trying to run tests for a package, the equivalent of `pnpm turbo run test --no-deps --scope=@iw/button`. This has a dependency on `@iw/log` so I've therefore configured my `turbo.json` file to include the `^build` step.

```
"test": {
    "dependsOn": ["^build"]
},
```

This however doesn't include build `@iw/log` because of the scope. I therefore need to pass `--include-dependencies` in to encourage Turborepo to run the build on any dependencies.

However this also now runs the `test` script against `@iw/log` which isn't what I wanted it to do.

### Expected Behavior

I expected to be able to run my tests on just a single package, automatically triggering the build steps - but without **also** running their tests.

### To Reproduce

This assumes you have pnpm setup:

```
git clone https://github.com/IPWright83/pnpm-monorepo
cd pnpm-monorepo
pnpm install
```

Then this will fail:
```
pnpm turbo run test --no-deps --scope=@iw/button -- -- --watchAll=false 
```

This will work, but attempts to run tests for `@iw/log` too as evidenced by:
>@iw/log:test: > @iw/log@0.1.0 test /home/ian/src/scale-fe/pnpm/packages/log
@iw/log:test: > jest --passWithNoTests "--watchAll=false"

```
pnpm turbo run test --no-deps --scope=@iw/button --include-dependencies -- -- --watchAll=false
```

**Comment by gsoltis** [comment]
This is unfortunately currently a known issue. Right now, you probably want `--include-dependencies` nearly every time you use `--scope` or `--since`. This can result in running extra tasks, but this will get pruned down soon.

For more details, this is because we currently remove any packages not selected by the various filter flags from the package dependency graph before calculating the task dependency graph. So, if a package (`@iw/log`) is not selected via flags (e.g. `--include-dependencies` is not present) it doesn't show up as a dependency of `@iw/button` when we go to resolve the dependencies of `@iw/button#test`. This is almost certainly not the desired behavior, and will be addressed in the future.

**Comment by IPWright83** [comment]
Thanks @gsoltis - is this related to the `--filter` flag that I've since seen talked about?

**Comment by gsoltis** [comment]
@IPWright83 I filed #912 to track the issue.

**Comment by IPWright83** [comment]
Thanks @gsoltis, I've subscribed to the other issue too to monitor. If this is now a useless duplicate feel free to close.
